"""Generate docs/decision_log.md: every cleaning decision, why, and how many rows it touched.

The counts are computed from the warehouse on every build, so the log can never drift out
of date the way a hand-written note would. If StatCan suppresses more cells next month, the
log says so.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import duckdb

from src.config import ROOT

LOG_PATH = ROOT / "docs" / "decision_log.md"

# (layer, decision, why, SQL returning one number: the rows affected)
DECISIONS = [
    ("raw", "LFS: kept 4 statistics, 2 data types and 4 age groups out of the full table",
     "The 1.18 GB file holds every combination; the dashboard needs headline series plus the "
     "standard errors that decide whether a move is real. Trend-cycle is dropped because "
     "StatCan revises its latest points heavily.",
     "SELECT count(*) FROM raw_lfs"),
    ("staging", "LFS: dropped rows suppressed by StatCan, status 'x'",
     "Suppressed for confidentiality or reliability, mostly small subgroups such as women 55+ "
     "in smaller provinces. These leave gaps inside series, which is why marts join prior "
     "months by calendar date rather than using LAG().",
     "SELECT count(DISTINCT (ref_date, geo, characteristic, gender, age_group, data_type)) "
     "FROM raw_lfs WHERE statistic = 'Estimate' AND status = 'x'"),
    ("staging", "LFS: standard errors left NULL where StatCan publishes none",
     "StatCan publishes them for seasonally adjusted series from 2001 only. Significance "
     "flags are NULL for earlier months rather than guessed. Rows below are seasonally "
     "adjusted rows with no standard error.",
     "SELECT count(*) FROM stg_lfs WHERE se_mom IS NULL AND data_type = 'Seasonally adjusted'"),
    ("staging", "CPI: kept only series on the 2002=100 base",
     "The raw file mixes 11 index bases; ratios across bases are meaningless. Rows below "
     "are rows on any other base, which must be 0; a data test fails otherwise.",
     "SELECT count(*) FROM stg_cpi WHERE index_base <> '2002=100'"),
    ("staging", "NHPI: dropped '..' and 'x' rows (no value)",
     "Not available or suppressed; nothing to analyse.",
     "SELECT count(*) FROM raw_nhpi WHERE value IS NULL"),
    ("staging", "NHPI: KEPT rows flagged 'E' (use with caution), with a flag column",
     "Dropping them would erase several smaller metros entirely; hiding the flag would "
     "overstate confidence. The dashboard marks them instead.",
     "SELECT count(*) FROM stg_nhpi WHERE use_with_caution"),
    ("staging", "Job vacancies: kept quality grades A to F next to each figure",
     "Grade F arrives with no value. Grades E and F are excluded from the unemployed per "
     "vacancy ratio and flagged as low quality.",
     "SELECT count(*) FROM raw_job_vacancies WHERE quality_grade = 'F'"),
    ("staging", "GDP: dropped '..' rows (no value)",
     "Seven series (for example the ICT sector) only start in 2007; earlier months are empty.",
     "SELECT count(*) FROM raw_gdp WHERE value IS NULL"),
    ("marts", "Labour: unemployment moves tested against 1.96 x StatCan's own standard error",
     "Separates real changes from sampling noise. Rows below are months where the monthly "
     "change in the national unemployment rate was NOT significant.",
     "SELECT count(*) FROM mart_labour_monthly WHERE geo = 'Canada' "
     "AND gender = 'Total - Gender' AND age_group = '15 years and over' "
     "AND NOT unemployment_rate_mom_significant"),
    ("marts", "Job market: vacancies joined to UNADJUSTED unemployment",
     "Vacancies are not seasonally adjusted; mixing adjusted and unadjusted series would "
     "build a seasonal pattern into the ratio. Rows below have a ratio.",
     "SELECT count(*) FROM mart_job_market_monthly WHERE unemployed_per_vacancy IS NOT NULL"),
    ("marts", "Anomalies: robust z-score (median and MAD) of the change, prior 36 months, "
     "|z| >= 3.5, at least 24 months of history",
     "A classic z-score scored the September 2020 unemployment drop as normal (-1.0) because "
     "the COVID spike inflated the standard deviation; the robust score gives -6.7. Rows "
     "below are all flagged anomalies across domains.",
     "SELECT count(*) FROM mart_anomalies"),
]


def write(con: duckdb.DuckDBPyConnection, path: Path = LOG_PATH) -> Path:
    built = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Decision log",
        "",
        f"Generated by `python -m src.build` on {built}. Do not edit by hand: the row counts "
        "are recomputed from the warehouse on every build.",
        "",
        "| # | Layer | Decision | Why | Rows affected |",
        "|---|---|---|---|---|",
    ]
    for i, (layer, decision, why, sql) in enumerate(DECISIONS, 1):
        count = con.execute(sql).fetchone()[0]
        cells = [str(i), layer, decision, why, f"{count:,}"]
        # A literal pipe (as in |z|) would split the markdown table cell.
        lines.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |")
    loads = con.execute(
        "SELECT table_name, source_pid, source_last_modified, row_count, max_ref_date "
        "FROM _load_log QUALIFY row_number() OVER (PARTITION BY table_name ORDER BY loaded_at DESC) = 1 "
        "ORDER BY table_name"
    ).fetchall()
    lines += ["", "## Source versions used in this build", "",
              "| Raw table | StatCan table | Published (Last-Modified) | Rows kept | Latest month |",
              "|---|---|---|---|---|"]
    for table, pid, modified, rows, max_ref in loads:
        lines.append(f"| {table} | {pid} | {modified} | {rows:,} | {max_ref} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    return path
